### ISSUE TITLE
Prestigio PAP4500DUO edify_defs file

### ISSUE THREAD

**Issue by prescott66** [dsixda/Android-Kitchen#12]
Hi.
I have created and tested config file in edify_defs folder for device Prestigio PAP4500DUO.
Please add file named "PAP4500DUO" in "edify_defs" folder
with this content to support it for another users:

change_mnt=yes

param1=ext4
param2=EMMC

param1_sdcard=vfat
param2_sdcard=MTD

sys_mnt=\/dev\/block\/mmcblk0p3
cache_mnt=\/dev\/block\/mmcblk0p4
boot_mnt=\/dev\/bootimg
data_mnt=\/dev\/block\/mmcblk0p5
sdcard_mnt=\/dev\/block\/mmcblk1p1

**Comment by dsixda** [comment]
Please send me a git pull request.  I don't spend much time at my computer.   Thanks.
