### ISSUE TITLE
Tools/edify_defs/maguro needs updating!?

### ISSUE THREAD

**Issue by manumanfred** [dsixda/Android-Kitchen#15]
So the issue is that when I build ROM via this Android Kitchen for Nexus (Takju) JB 4.2.2 the updater-script has HSSMC text but every other ROM has EMMC    ..... /*/0/  .....

Sometimes wen flashing my ROM (OTA) from another ROM causes boot loops or errors in homescreen...

I have checked updater-script and changed mount and format lines but still same issue.
Maybe Updater-binary is also old for JB 4.2.2?

Sorry I don't know much about creating flash-able ROM.

**Comment by dsixda** [comment]
Sorry, I have no idea.  I think it was created out of information that was submitted.  If you want to make a change please let me know or send a git pull request.  Thanks
