### ISSUE TITLE
Deodexing

### ISSUE THREAD

**Issue by iBotPeaches** [dsixda/Android-Kitchen#2]
There is a new baksmali/smali in development labeled 1.3.4-dev. I urge you when it comes out to change the method of deodexing.

Currently there is lots of hardcoded dependencies, which were needed back in the day and now aren't. Lots of people report problems deodexing ROMs, but then only use your kitchen :/ , and since some of the dependencies are bugged or wrong they blame apktool or smali/baksmali when its really the scripts their using.

In order to feed the mass population, I feel I should urge the developer(s) to update it  when free. smali v1.3.4 reads the odex file for dependencies so the actual use of the -c parameter is un-needed. Don't worry with all that classpath stuff.

So instead of a 1,000 line do_deodex file it can be brought down to

smali.jar -a API_LEVEL -d "../framework" -x "$file.odex" 
etc etc

**Comment by dsixda** [comment]
Thank you for the heads-up..  Yes, that's the problem of people not knowing
what they're doing and relying on the kitchen without learning. 

I'll update it when I have time, but I only really work on it at my own
pace, and people should not be using the kitchen and especially not the
de-odex routines -- most of it was written in early 2010 and it's outdated
by now.

Danial

On Mon, Jul 9, 2012 at 2:24 PM, Connor Tumbleson <
reply@reply.github.com

**Comment by iBotPeaches** [comment]
Makes sense, I didn't know. I'll fork the REPO and change it, and give you a little pull request. See if you like it, change what you want.

(when I have some free-time)

Thanks,
Connor

**Comment by dsixda** [comment]
Sounds good....
Thx
On Jul 10, 2012 9:55 AM, "Connor Tumbleson" <
reply@reply.github.com>
wrote:

**Comment by BurgerZ** [comment]
I can help too. You have separated bootclasspath variables for each apk. But I've written several functions that extract full bootclass from the kernel of the ROM and all apks are deodexed with it w/o errors. If there is no kernel in the ROM, then bootclasspath = "every file in the framework directory". If apk/jar is such like google's files I use googles frameworks to handle them.
P.S. Sorry for my bad English. I hope you can understand what I've written. :-)

**Comment by dsixda** [comment]
It's alright, but thanks for the offer.

@ibotpeaches - I can't find the new command syntax in the smali/baksmali page, although I probably didn't look well enough.  If you let me know what it is exactly I can make the change myself.  I'm more comfortable making my own changes due to the dependencies in different areas of the kitchen, and I don't want those to break.

**Comment by iBotPeaches** [comment]
@dsixda There is no change. Just run the same command without including anything into the -c parameter.

EX

```
   # Convert from odex to /out
   echo "Extracting the $(basename $file) out of .odex form.";
   java $commands -jar /home/$up/tools/baksmali.jar -a $api_level -d "../framework" -x $(basename $file)
```

That'll work for every apk/jar. No matter what. Thats my auto script, so its probably setup very different, but you get the point. I've yet to find a ROM I can't deodex with this method. As long as the ROM structure is correct and the JARs, etc are there. It'll work. Do JARs first, then APKs.

@BurgerZ The point of the new baksmali is to remove the need to do that.

**Comment by dsixda** [comment]
Thank you.  Easy change, and saves everyone a lot of pain.  Fix will be submitted soon after some testing.
