### ISSUE TITLE
problem in siging update.zip

### ISSUE THREAD

**Issue by ahmadii** [dsixda/Android-Kitchen#20]
hi
i done all of the steps successfully
but the last step which is to sign the zip file fails with the following error

Error: Unable to access jarfile signapk.jar

how to solve this problem?
thanks

**Comment by dsixda** [comment]
Likely you have a setup issue with Java.   Please do not post tech support questions here, this is only for bug reports.

**Comment by snizzr** [comment]
Same here. What seems to be the problem?
