### ISSUE TITLE
Samsung Galaxy Note3 special boot.img/recovery.img format

### ISSUE THREAD

**Issue by liuyix** [dsixda/Android-Kitchen#23]
Hi,
I recently get a Samsung Galaxy Note3 and unpack and repack the [CWM recovery for Galaxy Note3](http://forum.xda-developers.com/showthread.php?p=45959909) but it cannot flash the repacked image correctly -- After flashing it by Odin, I cannot boot into the recovery mode.
Hint:  _Xiaolu_ the author of `CWM for SGN3` has released a special version of [mkbootimg_tools](https://github.com/xiaolu/mkbootimg_tools) and turns out that it can correctly work.

**Comment by dsixda** [comment]
Hi, I'm not actively updating the kitchen anymore.  See page 1 of the xda
thread for details.  I don't have the means to keep up with the
never-ending updates.   You are welcome to fetch the project into your
local workspace and make the necessary updates to make it work for you.

**Comment by liuyix** [comment]
Ok, got it. I will fix it as soon as I have a chance.
