### ISSUE TITLE
Patch: Fix menu script so it can be called from anywhere.

### ISSUE THREAD

**Issue by bdmayes** [dsixda/Android-Kitchen#26]
I can't commit to this repo so I'm just going to attach a patch file here.  It looks like this is not really that active of a project, but I'll contribute this anyway.

The changes will figure out which directory menu is running from by resolving symlinks and so on.  Then it just uses pushd at the beginning and popd in all places where we exit (I just made a function to always call popd and use that everywhere instead of directly calling exit).

Apparently I can't attach .patch files, nor can I attach .txt files.  So here is the full patch, which you can just paste into a file and apply, then commit to the repo.

``` bash
diff --git a/menu b/menu
index 1186dfd..375a9c5 100755
--- a/menu
+++ b/menu
@@ -12,6 +12,27 @@

 version=0.224

+# function to pop the directory off the stack and exit
+function popExit {
+  popd > /dev/null 2>&1
+  exit $1
+}
+
+# Resolve all symlinks and such to figure out where we are called from.  Source:
+# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
+SOURCE="${BASH_SOURCE[0]}"
+while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
+  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+  SOURCE="$(readlink "$SOURCE")"
+  # if $SOURCE was a relative symlink, we need to resolve it relative to the path
+  # where the symlink file was located
+  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
+done
+
+# pushd to add the fully-resolved directory to the stack
+DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+pushd $DIR > /dev/null 2>&1
+cd $DIR

 if [ ! -e menu ]
 then
@@ -39,7 +60,7 @@ if [ $error_found == 1 ]
 then
   echo
   echo "Ensure you have installed the folders for the kitchen correctly."
-  exit 0
+  popExit 0
 fi


@@ -48,7 +69,7 @@ scripts/check_install_dir

 if [ "$?" == "1" ]
 then
-  exit 0
+  popExit 0
 fi

 scripts/init_kitchen
@@ -56,7 +77,7 @@ scripts/check_binaries

 if [ "$?" == "1" ]
 then
-  exit 0
+  popExit 0
 fi


@@ -112,7 +133,7 @@ do
       00) scripts/menu_legacy $version; continue;;
       99) scripts/build_rom;;
       u) scripts/about $version; continue;;
-      x) scripts/init_kitchen; clear; echo; echo "Goodbye."; echo; exit 1;;
+      x) scripts/init_kitchen; clear; echo; echo "Goodbye."; echo; popExit 1;;
       *) echo "Invalid option"; continue;;
     esac
   fi
```

**Comment by dsixda** [comment]
Hi, thanks for your update.  Unfortunately, I haven't played around with
the kitchen in several months, and I probably won't be able to test it at
the moment.  Is this compatible with Linux, Cygwin _and_ OS X?

**Comment by bdmayes** [comment]
I have no idea if it will work in cygwin...I can try to find a Windows box to test with.  It definitely works in Linux (which is where I wrote this).  We use this same pushd/popd approach in my scripts at work and most of the developers are on OS X.  I'm an outlier, running Ubuntu on my macbook, but I'll boot up my OS X partition and verify it works there.  If anyone else can test cygwin that would be great, but if not, I'll find a Windows box somewhere and try it.

I'll report back once I know more.
