### ISSUE TITLE
JUST ASKING SOMETHING IF YOU ALLOW

### ISSUE THREAD

**Issue by matriex** [dsixda/Android-Kitchen#31]
HI there
Since you abandon this project it is no longer updatable, CAN I TAKE THIS PROJECT AND MAKE CHANGES AND PROVIDE UPDATES FOR FUTURE IF YOU WILL ALLOW
AND IT IS STILL REMAINS YOURS
"I ONLY WANTED TO MAKE IT BETTER WITH CURRENT NEED"

Regards 
matrix

**Comment by dsixda** [comment]
Hi, the kitchen is very out of date, it has not been updated in 3 years. You can fork your own copy for your personal use but I cannot provide any support as I have almost completely forgotten how it works and it has been a while (I no longer use Android for daily use).  I do not recommend sharing the kitchen publicly as it will not be compatible with modern devices and will be full of issues.  Thanks

**Comment by matriex** [comment]
Oh ok thanks for reply
