### ISSUE TITLE
Application gcc is not installed

### ISSUE THREAD

**Issue by vinayaksankeet** [dsixda/Android-Kitchen#32]
After typing kitchen in cywgin
this error message "application gcc is not installed" 
is shown

**Comment by matriex** [comment]
Hi
if you are a linux user, then type in your terminal
"apt install gcc"    or     search the web
and if you are in cygwin ,install it while installing Cygwin terminal
read http://forum.xda-developers.com/attachment.php?attachmentid=2134346&d=1374469458
