### ISSUE TITLE
Options missing

### ISSUE THREAD

**Issue by SHAMDEN** [dsixda/Android-Kitchen#33]
Please help me sir..... 
When i command ./menu this it show some options but when i command  for advance mod it will show me only 8th options in there. What should i have to do there is missing 18 to 24 number options? Android kitchen is the very interesting thing I want to know more about this please sir help me I will be waiting for your answer........... ☺☺☺☺☺

**Comment by HarEllis** [comment]
Android kitchen is dead move on

**Comment by dsixda** [comment]
Sorry, I haven't used or updated this kitchen in over 4 years. You may want to check xda-developers for newer kitchens.

**Comment by SHAMDEN** [comment]
Sir,  If you have anything new to create ROM like that please send me the link or give the name.

**Comment by dsixda** [comment]
I haven't customized or regularly used an Android device since 2013, sorry.  There are more current developers out there that may be of help to you.
